### ISSUE TITLE
Support for signals

### ISSUE THREAD

**Issue by marianatuma** [rensjaspers/ngx-load-with#59]
Is there currently support for signals? If not, it would be a nice feature to add.

**Comment by rensjaspers** [comment]
Hi there,

Thanks for asking about signal support! The library doesn't use signals itself. But you can use signals in your components with Angular 17.1. To use signals with `ngxLoadWith`, pass the data from `ngxLoadWith` to a child component that has signal inputs. Here's an example of how to do it ([Check it out on StackBlitz](https://stackblitz.com/edit/stackblitz-starters-aku8xe)):

```typescript
import { Component, computed, input, signal } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import { NgxLoadWithDirective } from 'ngx-load-with';
import { interval } from 'rxjs';
import 'zone.js';

@Component({
  selector: 'app-child',
  standalone: true,
  template: `
  count: {{count()}}
  double: {{double()}}
  `,
})
export class ChildComponent {
  count = input.required<number>(); // <-- this is a signal input
  double = computed(() => this.count() * 2); 
}

@Component({
  selector: 'app-root',
  standalone: true,
  template: `
    <app-child *ngxLoadWith="count$ as count" [count]="count"></app-child>
  `,
  imports: [ChildComponent, NgxLoadWithDirective],
})
export class App {
  count$ = interval(1000);
}

bootstrapApplication(App);
```

I hope this helps. If you have more questions, feel free to ask.
